INSERT INTO questions (question_text, parent_question_id) VALUES 
('Is your character a plumber?', NULL),
('Is your character from a Nintendo franchise?', NULL),
('Is your character a Greek god?', NULL),
('Is your character from a Halo game?', NULL),
('Is your character a witcher?', NULL),
('Does your character have a blue hedgehog?', NULL),
('Is your character from a Final Fantasy game?', NULL),
('Is your character a hero from Hyrule?', NULL),
('Is your character a cowboy?', NULL),
('Is your character from Red Dead Redemption?', NULL),
('Is your character a Saiyan?', NULL),
('Is your character from One Piece?', NULL),
('Does your character have super speed training?', NULL),
('Does your character wear glasses?', NULL),
('Is your character a Titan shifter?', NULL),
('Is your character from Tomb Raider?', NULL),
('Is your character from The Last of Us?', NULL),
('Is your character a founder of a major company?', NULL),
('Did your character drop out of college?', NULL),
('Is your character from Apple?', NULL),
('Is your character a co-founder of Google?', NULL),
('Did your character create a major programming language?', NULL),
('Is your character primarily a streamer?', NULL),
('Does your character have a popular YouTube channel?', NULL),
('Is your character known for gaming content?', NULL),
('Does your character do react videos?', NULL),
('Is your character known for battle royale games?', NULL),
('Is your character a singer who also acts?', NULL),
('Is your character known as King of Rock and Roll?', NULL),
('Is your character a lead singer of a band?', NULL),
('Is your character an actor who has played in action movies?', NULL),
('Did your character win an Oscar?', NULL),
('Is your character known for playing a detective?', NULL),
('Is your character a goalkeeper who plays for Bayern Munich?', NULL),
('Is your character an esports streamer?', NULL),
('Is your character known for Among Us?', NULL),
('Is your character a female singer?', NULL),
('Is your character a member of LGBTQ community?', NULL),
('Is your character an actress who has played in superhero movies?', NULL);